Correct pagination
meilisearch/meilisearch-rails pull request #10
Opened 2021-04-14 17:48 UTC by CaroFG

2021-04-15 08:30 UTC, curquiza commented
Can you explain which bug this PR fixes?

2021-04-15 09:02 UTC, CaroFG commented
In the front-end: 
Kaminari pagination didn't work properly because and an error was raised when trying to change the page because the page param was sent as a string instead of an integer. 
Will_paginate would send all the results to all the pages.

2021-04-15 15:25 UTC, curquiza requested changes
small change 😇

2021-04-15 15:25 UTC, curquiza commented on lib/meilisearch/pagination/will_paginate.rb
> +          start = (options[:page] - 1 ) * options[:per_page]
```suggestion
          start = (options[:page] - 1) * options[:per_page]
```

2021-04-16 09:27 UTC, curquiza approved these changes
🚀
merge when you want ;)

2021-04-19 07:20 UTC, CaroFG commented
bors try

2021-04-19 07:23 UTC, CaroFG commented
bors merge

2021-04-19 07:24 UTC, merged