Add CONTRIBUTING file
meilisearch/meilisearch-rails pull request #11
Opened 2021-04-20 08:22 UTC by CaroFG

Closes #2

2021-04-20 13:55 UTC, curquiza requested changes

2021-04-20 13:55 UTC, curquiza commented on CONTRIBUTING.md
> +
```suggestion

First, you need to run a MeiliSearch instance:

```bash
docker run -p 7700:7700 getmeili/meilisearch:latest ./meilisearch --no-analytics=true
```bash
```

2021-04-20 13:55 UTC, curquiza commented on CONTRIBUTING.md
> +Make a PR modifying the file [`lib/meilisearch.version.rb`](/lib/meilisearch.version.rb) with the right version.
```suggestion
Make a PR modifying the file [`lib/meilisearch/version.rb`](/lib/meilisearch/version.rb) with the right version.
```

2021-04-20 13:55 UTC, curquiza commented on CONTRIBUTING.md
> +
Sorry I cannot add a real suggestion because of the ```

2021-04-20 13:55 UTC, curquiza commented on CONTRIBUTING.md
> +rails server
```suggestion
bundle exec rails db:create
bundle exec rails db:migrate
bundle exec rails db:seed
bundle exec rails server
```

2021-04-20 13:55 UTC, curquiza commented on CONTRIBUTING.md
> +rails server
To be sure to execute the rails installed by bundler in your project environment instead of the global rails installed in your local machine

2021-04-21 09:14 UTC, curquiza approved these changes
Thanks @CaroFG! 😄

2021-04-21 09:15 UTC, curquiza commented
merge when you want, the playground will arrive soon 🙂

2021-04-21 09:15 UTC, curquiza commented
But you can wait for #9 if you prefer of course 😇

2021-04-21 10:09 UTC, CaroFG commented
bors try

2021-04-21 10:13 UTC, CaroFG commented
bors merge

2021-04-21 10:14 UTC, merged