Rename meilisearch_host to meilisearch_url
meilisearch/meilisearch-rails pull request #197
Opened 2022-10-06 15:15 UTC by AdoPi

Hello :wave: 

I think the name meilisearch_host is a little bit confusing and error prone as it is used for an URL and not a real hostname.

I've changed the name "host" to use "url" instead.

## PR checklist
Please check if your PR fulfills the following requirements:
- [ X] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [X ] Have you read the contributing guidelines?
- [X ] Have you made sure that the title is accurate and descriptive of the changes?

2022-10-11 07:01 UTC, brunoocasali requested changes
Hello @AdoPi thanks a lot for your contribution!

I just asked for one fix, after that it will be good to go!

2022-10-11 07:01 UTC, brunoocasali commented on docker-compose.yml
> +      - MEILISEARCH_URL=http://meilisearch:7700
Can you change to MEILISEARCH_HOST again?
```suggestion
      - MEILISEARCH_HOST=http://meilisearch:7700
```

All the other SDKs, share the same principles, and if I change here I will have to change in every other repo, I agree with your suggestion and I will create an issue for that :)

But for now to merge your PR I have to ask you to change the docker config back ;)

2022-10-11 09:36 UTC, brunoocasali requested changes
Sorry if I was not so clear last comment, but you will also have to change in the code where we do explicitly references of the `MEILISEARCH_HOST`, otherwise the docker configuration will not work :)

2022-10-11 09:36 UTC, brunoocasali commented on spec/spec_helper.rb
> +      meilisearch_url: ENV.fetch('MEILISEARCH_URL', 'http://127.0.0.1:7700'),
```suggestion
      meilisearch_url: ENV.fetch('MEILISEARCH_HOST', 'http://127.0.0.1:7700'),
```

2022-10-11 09:36 UTC, brunoocasali commented on spec/support/1_initialize_meilisearch.rb
> +  meilisearch_url: ENV.fetch('MEILISEARCH_URL', 'http://127.0.0.1:7700'),
```suggestion
  meilisearch_url: ENV.fetch('MEILISEARCH_HOST', 'http://127.0.0.1:7700'),
```

2022-10-11 09:36 UTC, brunoocasali commented on spec/integration_spec.rb
> +    MeiliSearch::Rails.configuration = { meilisearch_url: ENV.fetch('MEILISEARCH_URL', 'http://127.0.0.1:7700'),
```suggestion
    MeiliSearch::Rails.configuration = { meilisearch_url: ENV.fetch('MEILISEARCH_HOST', 'http://127.0.0.1:7700'),
```

2022-10-11 09:36 UTC, brunoocasali commented on spec/integration_spec.rb
> +      meilisearch_url: ENV.fetch('MEILISEARCH_URL', 'http://127.0.0.1:7700'),
```suggestion
      meilisearch_url: ENV.fetch('MEILISEARCH_HOST', 'http://127.0.0.1:7700'),
```

2022-10-11 09:36 UTC, brunoocasali commented on spec/integration_spec.rb
> +    MeiliSearch::Rails.configuration = { meilisearch_url: ENV.fetch('MEILISEARCH_URL', 'http://127.0.0.1:7700'),
```suggestion
    MeiliSearch::Rails.configuration = { meilisearch_url: ENV.fetch('MEILISEARCH_HOST', 'http://127.0.0.1:7700'),
```

2022-10-11 09:36 UTC, brunoocasali commented on playground/config/initializers/meilisearch.rb
> +    meilisearch_url: ENV.fetch('MEILISEARCH_URL', 'http://localhost:7700'),
```suggestion
    meilisearch_url: ENV.fetch('MEILISEARCH_HOST', 'http://localhost:7700'),
```

2022-10-11 09:36 UTC, brunoocasali commented on CONTRIBUTING.md
> +MEILISEARCH_URL="http://127.0.0.1:7700"
```suggestion
MEILISEARCH_HOST="http://127.0.0.1:7700"
```

2022-10-11 11:54 UTC, AdoPi commented
Oops sorry I didn't understand, I'm going to change all the occurences

2022-10-18 16:42 UTC, brunoocasali approved these changes
Thanks a lot for your patience and your contribution! ❤️ 

bors merge

2022-10-18 16:47 UTC, merged

2022-10-18 16:47 UTC, brunoocasali commented
_This message is sent automatically_

Thanks again for contributing to Meilisearch :heart:
If you are participating in [Hacktoberfest](https://blog.meilisearch.com/contribute-hacktoberfest-2022/), and you would like to receive some gift from Meilisearch too, please complete [this form](https://meilisearch.typeform.com/to/idt5qugY).