Fix custom primary key
meilisearch/meilisearch-rails pull request #23
Opened 2021-05-11 17:21 UTC by CaroFG

2021-05-11 17:49 UTC, curquiza requested changes

2021-05-11 17:49 UTC, curquiza commented on lib/meilisearch-rails.rb
> +      @index = client.get_or_create_index(index_uid, primary_key)
```suggestion
      primary_key = options[:primary_key].to_s ||  MeiliSearch::IndexSettings::DEFAULT_PRIMARY_KEY
      @index = client.get_or_create_index(index_uid, { primaryKey: primary_key })
```

2021-05-11 17:49 UTC, curquiza commented on lib/meilisearch-rails.rb
> +      pk
```suggestion
      options[:primary_key] || MeiliSearch::IndexSettings::DEFAULT_PRIMARY_KEY
```

2021-05-11 17:49 UTC, curquiza commented on lib/meilisearch-rails.rb
> +      @index = client.get_or_create_index(index_uid, primary_key)
You should add `DEFAULT_PRIMARY_KEY` in `MeiliSearch::IndexSettings` of course 😇

2021-05-12 12:12 UTC, curquiza approved these changes
Well done Caro :)

2021-05-12 12:23 UTC, CaroFG commented
bors merge

2021-05-12 12:24 UTC, merged