Add return value to ms_index!
meilisearch/meilisearch-rails pull request #289
Opened 2023-09-21 13:06 UTC by ellnix

# Pull Request

## Related issue
Fixes #271

## What does this PR do?
- Changes `#ms_index!` to pass along the task hash provided by the meilisearch gem
- Adds tests for the three possible return types 

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

I'm new to this project, so I tried to keep the solution as unopinionated as possible. Please feel free to suggest changes to the implementation.

2023-10-06 12:43 UTC, brunoocasali requested changes
Hi @ellnix, thanks a lot for your contribution!

2023-10-06 12:43 UTC, brunoocasali commented on spec/integration_spec.rb
> +      a_hash_including('taskUid')
Did you forget to add a different attribute here? In any case remove one of the `taskUid`

2023-10-06 12:43 UTC, brunoocasali commented on spec/integration_spec.rb
> +
```suggestion
```

2023-10-06 12:43 UTC, brunoocasali commented on spec/integration_spec.rb
> +      doc = DisabledEnqueuedDocument.create! name: 'test'
Can you remind me why this should return `nil`?

2023-10-06 12:43 UTC, brunoocasali commented on lib/meilisearch-rails.rb
> +          tasks.first
I don't like the approach of returning multiple types here. As a developer consuming the method, I would always have to check the response to use the response. So I suggest returning the tasks directly.

2023-10-06 12:43 UTC, brunoocasali commented on lib/meilisearch-rails.rb
> +          tasks.first
But better thinking about it, I don't know if there is a use case to return multiple tasks. Can you check that?

2023-11-03 17:38 UTC, brunoocasali commented on lib/meilisearch-rails.rb
> +          tasks.first
As agreed by Discord, we will make this return a single type an Array

2023-11-29 09:50 UTC, ellnix commented
@brunoocasali sorry for being inactive this month, this and the other PRs should be ready to merge if you agree with the changes.

2023-12-11 20:38 UTC, brunoocasali commented
Hey @ellnix I asked some questions in the last review, could you check them?

2023-12-12 12:00 UTC, brunoocasali approved these changes
LGTM!

2023-12-12 12:01 UTC, ellnix commented
bors merge

2023-12-12 12:03 UTC, merged

2023-12-12 13:59 UTC, mech commented
Wonderful!