Warn when you make missing attribute searchable
meilisearch/meilisearch-rails pull request #293
Opened 2023-09-27 14:21 UTC by ellnix

# Pull Request

## Related issue
Fixes #168

## What does this PR do?
- In addition to adding a warning as suggested in #168 it also adds a `#logger` method to `MeiliSearch::Rails` which is similar to Rails having its own `Rails#logger` 

## PR checklist
Please check if your PR fulfills the following requirements:
- [X] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [X] Have you read the contributing guidelines?
- [X] Have you made sure that the title is accurate and descriptive of the changes?

2023-10-06 12:51 UTC, brunoocasali requested changes
Thanks a lot @ellnix, for all of your work here!

I made some comments I would like you to reevaluate before we can merge this.

2023-10-06 12:51 UTC, brunoocasali commented on lib/meilisearch-rails.rb
> +
```suggestion
```

2023-10-06 12:51 UTC, brunoocasali commented on lib/meilisearch-rails.rb
> +        if (searchables = meilisearch_settings.get_setting(:searchable_attributes)) &&
It is okay to take some extra new lines to create the variables first. This way it will be easier to understand the logic behind the alert.

2023-10-06 12:51 UTC, brunoocasali commented on spec/integration_spec.rb
> +
```suggestion
```

2023-10-06 12:51 UTC, brunoocasali commented on spec/integration_spec.rb
> +  let(:others) { Class.new(People) { def self.name = "People" } }
Call it `people_class` or something like that, it will be easier to read afterwards.

2023-10-06 12:51 UTC, brunoocasali commented on spec/integration_spec.rb
> +        searchable_attributes [:first_name, :last_name]
```suggestion
      attribute :first_name
      searchable_attributes [:first_name, :last_name]
```

2023-10-06 12:51 UTC, brunoocasali commented on lib/meilisearch-rails.rb
> +        @logger ||= (::Rails.logger || Logger.new($stdout))
Nice catch!

2023-10-06 13:51 UTC, ellnix commented
I believe I fixed the issues suggested, I had made some really strange decisions on this PR.

I also removed one place where I used the new ruby 3 method definition syntax which would have broken compatibility with ruby 2.x in the test suite.

2023-10-06 13:54 UTC, brunoocasali commented
> I believe I fixed the issues suggested, I had made some really strange decisions on this PR.
> 
> I also removed one place where I used the new ruby 3 method definition syntax which would have broken compatibility with ruby 2.x in the test suite.

Nice, as soon you fix them we will be good to go, thanks a lot for your effort @ellnix!

2023-11-01 17:09 UTC, ellnix commented
@brunoocasali this should be good to go.

2023-11-03 17:17 UTC, brunoocasali approved these changes
@ellnix thanks for this fix 🎉 

Thanks a lot for your patience and your smart work here ❤️

2023-11-03 18:18 UTC, ellnix commented
bors merge

2023-11-03 18:20 UTC, merged